name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'r*' # Push events to matching v*, i.e. v1.0, v20.15.10
env: 
  GLOB_PATTERN: 'r[0-9][0-9][0-9][0-9]'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      REV: ${{ steps.vars.outputs.REV }}
      NUM: ${{ steps.vars.outputs.NUM }}
      OLD_REV: ${{ steps.vars.outputs.OLD_REV }}
      
    steps:
      - uses: actions/checkout@v2
      - name: Setting Variables
        id: vars
        shell: bash
        run: |
          echo "리비전을 파싱합니다..."
          echo "::set-output name=REV::$(git describe --match ${{ env.GLOB_PATTERN }} --abbrev=0 --tags ${{ github.sha }})"
          echo "이번 리비전: ${{ outputs.REV }}"
          echo "이거는: ${{ github.ref }}"
          echo '::set-output name=NUM::$({${{ outputs.REV }}:2})'
          echo '::set-output name=NUM::$(expr ${{ outputs.NUM }} - 1)'
          echo '::set-output name=NUM::$(printf "%04d\n" ${{ outputs.NUM }})'
          echo "::set-output name=OLD_REV::$(\r${{ outputs.NUM }})"
          echo "이전 리비전: ${{ outputs.OLD_REV }}"

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.vars.outputs.REV }}
          body: |
            [Diff since ${{ steps.vars.outputs.OLD_REV }}](https://github.com/yongheekim-dev/GithubTagActionTest/compare/${{ steps.vars.outputs.OLD_REV }}...${{ steps.vars.outputs.REV }})
          draft: false
          prerelease: false
